version: '2'

services:
    db:
      image: mysql:5.6
      volumes:
        - "./.data/db:/var/lib/mysql"
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ports:
        - "3306:3306"
      networks:
        - web-network
    web:
      build: .
      ports:
        - '80:80'
      volumes:
        - ${APP_PATH}:/var/www/html/
        - ./logs:/var/log/apache2/
      environment:
        DB_PASSWORD: ${MYSQL_PASSWORD}
        DB_USER: ${MYSQL_USER}
        DB_HOST: ${MYSQL_HOST}
        DB_PORT: ${MYSQL_PORT}
        DB_DRIVER: ${MYSQL_DRIVER}
        DB_PERFIX: ${MYSQL_PREFIX}
        DB_NAME: ${MYSQL_DATABASE}
      networks:
        - web-network
    phpmyadmin:
      image: corbinu/docker-phpmyadmin
      links:
          - db:db
      ports:
        - 8080:80
      environment:
          MYSQL_USERNAME: ${MYSQL_DATABASE}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
          MYSQL_PORT_3306_TCP_ADDR: db
      networks:
        - web-network

networks:
  web-network:
    driver: bridge